#!/bin/bash
clear
if [ "$#" -le 0 ] || [ "$#" -ge 2 ] 

then 
	echo "Invalid number of arguments"

	exit 0
fi

if [ -d "$1" ] 

then
	cd "$1"
	for file in * 
	do
		if [-d "$file" ]
		then 
			continue
		else
			grep "text" $file
		fi
	done
	exit 1		
else echo "$1" not a directory
fi

