#!/bin/bash

clear

filename=$1
lineNumber=$(wc -l < $filename)

if [[ $((lineNumber % 2)) -eq 0 ]] 
then 
	echo "This file has an even number of lines."

else 
	echo "This file has an odd number of lines."
fi




